### ISSUE TITLE
Commentaires

### ISSUE THREAD

**Issue by ba13malick** [akakpodorothee/formulaire_js#1]
Ne pas oublier de commenter chaque ligne de ton code JavaScript

**Comment by akakpodorothee** [comment]
OK. Merci coach

**Comment by ba13malick** [comment]
Les commentaires devraient être plus descriptifs des actions entreprises par le code. Tu décris ce que ta méthode ou fonction est entrain de faire 
ex: 
// Récuperation des données saisies
// selection de l'email
etc..

**Comment by akakpodorothee** [comment]
ok
